In [1]:
import torch 
import numpy as np
import pandas as pd

In [5]:
inputs = torch.tensor(
    [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]],
    dtype=torch.float32
)

weights = torch.tensor(
    [[0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]],
    dtype=torch.float32
)

biases = torch.tensor(
    [2.0,3.0,0.5],
    dtype=torch.float32
)

In [6]:
def layer(inputs, weights, biases):
    """Pure python NN Layer

    Args:
        inputs (list): inputs from previous layer
        weights (list): weights of each neuron in layer
        biases (list): biases of each neuron in layer

    Returns:
        list: output of each neuron in layer 
    """
    layer_outputs = []    
    for neuron_weights, neuron_bias in zip(weights, biases):
        neuron_output=0
        for n_input, weight in zip(inputs, neuron_weights):
            neuron_output += n_input*weight
        neuron_output +=neuron_bias
        layer_outputs.append(neuron_output)
    return layer_outputs

layer(inputs, weights, biases)

[tensor([4.5500, 5.0500, 0.1500, 4.5000]),
 tensor([1.2900, 0.1520, 6.2680, 2.2220]),
 tensor([-0.5550, -0.9110,  0.5510, -0.8260])]

In [7]:
def layer_vec(inputs, weights, biases):
    """PyTorch vectorized NN Layer

    Args:
        inputs (torch.tensor): inputs from previous layer
        weights (torch.tensor): weights of each neuron in layer
        biases (torch.tensor): biases of each neuron in layer

    Returns:
        torch.tensor: output of each neuron in layer 
    """
    cummulative = torch.matmul(inputs, weights.T) + biases
    return cummulative

In [8]:
layer_vec(inputs, weights, biases)

tensor([[ 4.8000,  1.2100,  2.3850],
        [ 8.9000, -1.8100,  0.2000],
        [ 1.4100,  1.0510,  0.0260]])