In [1]:
import torch 
import numpy as np
import pandas as pd

In [5]:
inputs1 = torch.tensor(
    [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]],
    dtype=torch.float32
)

weights1 = torch.tensor(
    [[0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]],
    dtype=torch.float32
)

biases1 = torch.tensor(
    [2.0,3.0,0.5],
    dtype=torch.float32
)

In [16]:
def layer(inputs:list, weights:list, biases:list) -> list:
    """Pure python NN Layer

    Args:
        inputs (list): inputs from previous layer
        weights (list): weights of each neuron in layer
        biases (list): biases of each neuron in layer

    Returns:
        list: output of each neuron in layer 
    """
    layer_outputs = []
    for neuron_input in inputs:
        neuron_output = []
        for neuron_weights, neuron_bias in zip(weights, biases):
            output_vals = 0
            for n_input, weight in zip(neuron_input, neuron_weights):
                output_vals += n_input*weight
            output_vals += neuron_bias
            neuron_output.append(output_vals)
        layer_outputs.append(neuron_output)
    return layer_outputs

layer(inputs1.tolist(), weights1.tolist(), biases1.tolist())

[[4.80000002682209, 1.209999918937683, 2.385000005364418],
 [8.90000006556511, -1.8100001215934753, 0.19999997317790985],
 [1.410000077784062, 1.0509998478889457, 0.025999927461146655]]

In [7]:
def layer_vec(inputs:torch.tensor, weights:torch.tensor, biases:torch.tensor):
    """PyTorch vectorized NN Layer

    Args:
        inputs (torch.tensor): inputs from previous layer
        weights (torch.tensor): weights of each neuron in layer
        biases (torch.tensor): biases of each neuron in layer

    Returns:
        torch.tensor: output of each neuron in layer 
    """
    cummulative = torch.matmul(inputs, weights.T) + biases
    return cummulative

In [8]:
output1 = layer_vec(inputs1, weights1, biases1)

tensor([[ 4.8000,  1.2100,  2.3850],
        [ 8.9000, -1.8100,  0.2000],
        [ 1.4100,  1.0510,  0.0260]])

# Multi layer implementation 

In [36]:
X = torch.tensor(
    [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]],
    dtype=torch.float32
)

class Layer_Dense:
    def __init__(self, n_inputs:int, n_neurons:int):
        self.weights = torch.randn(n_inputs, n_neurons)
        self.biases = torch.zeros((1, n_neurons))
    def forward(self, inputs:torch.tensor):
        self.output = torch.matmul(inputs, self.weights) + self.biases

In [45]:
L1 = Layer_Dense(4, 5)
L2 = Layer_Dense(5, 2)

In [46]:
L1.forward(X)
print(L1.output)
L2.forward(L1.output)
print(L2.output)

tensor([[-0.5100, -3.8524, -6.8966, -2.6354, -2.8712],
        [ 0.2910, -2.1024, -7.7058,  3.5387, -7.5256],
        [ 6.8566, -0.0754, -4.4648, -0.6942, -3.4342]])
tensor([[  0.2450, -16.0456],
        [  3.8542, -16.7942],
        [  5.5154,  -8.7893]])
